CREATE TABLE user
(
    USER_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    FNAME        VARCHAR(255),
    LNAME        VARCHAR(255),
    EMAIL_ID     VARCHAR(255),
    CREATED_BY   VARCHAR(255),
    UPDATED_BY   VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP

);